Create coq-settings.md
kaist-cp/helpdesk pull request #112
Opened 2019-12-04 13:38 UTC by drzix

as you said.

Thanks.

2019-12-04 13:41 UTC, jeehoonkang commented on coq-settings.md
> +- You had better install Coq with Opam: `opam install coq` (More detail information is [here](https://coq.inria.fr/opam-using.html))
- 제목을 좀더 의미있게.  Install 정도가 무난해 보입니다.
- "You had better"는 마피아가 쓰는 말입니다.   "Install Coq using OPAM" 정도로 바꾸세요.
- `.emacs.d/init.el`을 이 파일에 옮기기보다는 다른 파일에 넣고 링크하세요.  아예 폴더를 하나 만드는게 좋을 것 같습니다.  `coq`?
- README.md에서 `coq/README.md`로 가는 링크 걸어주세요.

2019-12-04 13:41 UTC, jeehoonkang commented on coq-settings.md
> +- You had better install Coq with Opam: `opam install coq` (More detail information is [here](https://coq.inria.fr/opam-using.html))
아 그리고 맞춤법 검사기도... `C-x ispell` in emacs

2019-12-04 13:46 UTC, drzix commented on coq-settings.md
> +- You had better install Coq with Opam: `opam install coq` (More detail information is [here](https://coq.inria.fr/opam-using.html))
마피아....... 넵

2019-12-04 13:55 UTC, jeehoonkang commented on coq-settings.md
> +- **"Prof. Kang's `~/.emacs.d/init.el`"** is below.
이런 종류의 문서에서 저는 @jeehoonkang으로 지칭해주세요

2019-12-04 14:15 UTC, jeehoonkang requested changes

2019-12-04 14:15 UTC, jeehoonkang commented on README.md
> +  (too many) exercises---they are the essence of the book. You can learn how to install Coq and set your IDE at [here](coq/README.md)
- "setup"
- "at here" -> "here"

2019-12-04 14:15 UTC, jeehoonkang commented on coq/README.md
> +## INSTALL
다른 지점에선 전부 Install 과 같이 썼는데, 스타일을 통일하면 어떨까 해요.

2019-12-04 14:15 UTC, jeehoonkang commented on coq/README.md
> +  - (in Ubuntu) `apt install emacs`
Nested enumeration은 다른 기호를 쓰는게 어떨까 합니다..

2019-12-04 14:15 UTC, jeehoonkang commented on coq/README.md
> +You can learn more commands at [here](https://proofgeneral.github.io/doc/master/userman/index#Top)
"at here" -> "here"

2019-12-04 14:15 UTC, jeehoonkang commented on coq/init.el
> +    (message nil)))
newline

2019-12-05 01:46 UTC, jeehoonkang commented on coq/README.md
> +- Use Emacs, not CoqIDE:
One last thing.  I'd like not to discourage coqide here.  Please say you have two options, and just give a link to coqide, and explain emacs in details.

Besides, LGTM

2019-12-06 00:09 UTC, merged