ADD: Detailed E-mail guide
kaist-cp/helpdesk pull request #155
Opened 2020-07-30 02:07 UTC by coolofficials

교수님, 이메일 사용 관련하여 제가 착오 있었던 부분 관련하여 Guide를 추가했습니다. 검토해보시고 마음에 드시면 merge 해주시면 좋을 것 같습니다.

2020-07-30 04:52 UTC, jeehoonkang requested changes

2020-07-30 04:52 UTC, jeehoonkang commented on README.md
> +  - enable __Smtp__. <br>
- "SMTP"
- 강조를 위해 __ 대신 **를 쓰는게 어떨지 제안드립니다.  다른 곳에서 다 그렇게 되어있어서..

2020-07-30 04:52 UTC, jeehoonkang commented on README.md
> +  - go to kaist e-mail system.
말을 좀 줄일 수 있지 않을가 합니다.  URL도 적어주세요

```
- Go to mail.kaist.ac.kr > Settings and enable "SMTP".
- ...
```

2020-07-30 04:52 UTC, jeehoonkang commented on README.md
> +  - Add {firstname}.{lastname}@kaist.ac.kr.
"Add ... and set it as the default address."

2020-07-30 04:52 UTC, jeehoonkang commented on README.md
> +  - go to kaist e-mail system.
이외에 다른 곳도 혹시 말 바꿀 수 있을지 알아봐주세요.

2020-07-30 05:20 UTC, lkaybob reviewed
알림이 와서 잠깐 확인하고 저도 코멘트 남깁니다.
* 최종 머지 전 각 문장의 시작을 대문자로 바꿔주시는 것이 일관성 있어 보여 좋을 것 같습니다.

2020-07-30 05:20 UTC, lkaybob commented on README.md
> +__[Set up guide]__
Heading 5로 하는 것을 제안합니다.

```suggestion
##### Set up guide
```

2020-07-31 03:26 UTC, coolofficials commented
@jeehoonkang ping. 수정 사항 전부 반영했습니다.

2020-07-31 03:42 UTC, coolofficials commented on README.md
> +__[Set up guide]__
[ ] 가 없으니 preview 상 Heading 4와 5의 구분이 명확하지 않아서
##### [Set up guide]와 같이 남기도록 하겠습니다.

2020-07-31 03:52 UTC, jeehoonkang requested changes

2020-07-31 03:52 UTC, jeehoonkang commented on README.md
> +- Write [proper formal emails](https://www.wikihow.com/Write-a-Formal-Email). (__important!__ do not markup emails.)
- 이건 "Set up guide" 에 해당하는 내용이 아닙니다.
- 저는 "Configure the Gmail account to send from {firstname}.{lastname}@kaist.ac.kr." 의 하위 항목으로 `    + Go to ...` 와 같이 작성하는게 좋겠습니다.

2020-07-31 04:50 UTC, coolofficials commented
https://github.com/kaist-cp/helpdesk/pull/155#discussion_r463391475

해당 코멘트 관련 수정사항 반영하였습니다.
@jeehoonkang ping

2020-07-31 05:17 UTC, merged